[project]
name = "project1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.6",
    "gunicorn>=23.0.0",
    "pywhatkit>=5.4",
    "twilio>=9.4.2",
    "uvicorn>=0.34.0",
]
